// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Appointment struct {
	ID              int64     `json:"id"`
	PsychologistID  int64     `json:"psychologist_id"`
	PatientID       int64     `json:"patient_id"`
	StartTime       time.Time `json:"start_time"`
	DurationMinutes int64     `json:"duration_minutes"`
}

type Patient struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	PsychologistID int64          `json:"psychologist_id"`
	Email          string         `json:"email"`
	Phone          sql.NullString `json:"phone"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Psychologist struct {
	ID    int64          `json:"id"`
	Name  string         `json:"name"`
	Email string         `json:"email"`
	Phone sql.NullString `json:"phone"`
}

type ScheduleConfig struct {
	ID             int64 `json:"id"`
	PsychologistID int64 `json:"psychologist_id"`
	DayOfWeek      int64 `json:"day_of_week"`
	StartHour      int64 `json:"start_hour"`
	EndHour        int64 `json:"end_hour"`
}
